//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

//
// SDK Root: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk.sdk
//


@class DVTDirectoryBasedCustomDataStore, DVTFilePath, NSData, NSOperationQueue, NSSet;

@protocol DVTDirectoryBasedCustomDataStoreDelegate <NSObject>

@optional
- (void)customDataStore:(DVTDirectoryBasedCustomDataStore *)arg1 removeItemAtFilePath:(DVTFilePath *)arg2 completionQueue:(NSOperationQueue *)arg3 completionBlock:(void (^)(BOOL, NSError *))arg4;
- (void)customDataStore:(DVTDirectoryBasedCustomDataStore *)arg1 moveItemAtFilePath:(DVTFilePath *)arg2 toFilePath:(DVTFilePath *)arg3 completionQueue:(NSOperationQueue *)arg4 completionBlock:(void (^)(BOOL, NSError *))arg5;
- (void)customDataStore:(DVTDirectoryBasedCustomDataStore *)arg1 writeData:(NSData *)arg2 toFilePath:(DVTFilePath *)arg3 completionQueue:(NSOperationQueue *)arg4 completionBlock:(void (^)(BOOL, NSError *))arg5;
- (void)customDataStore:(DVTDirectoryBasedCustomDataStore *)arg1 makeFilePathsWritable:(NSSet *)arg2 completionQueue:(NSOperationQueue *)arg3 completionBlock:(void (^)(BOOL, NSError *))arg4;
@end

