//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

//
// SDK Root: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk.sdk
//


@class DVTSourceTextScrollView, NSEvent, NSScroller;

@protocol DVTSourceTextScrollViewDelegate <NSObject>

@optional
- (NSScroller *)scrollView:(DVTSourceTextScrollView *)arg1 pointInVisibleScroller:(struct CGPoint)arg2;
- (void)scrollViewDidSetFrameSize:(DVTSourceTextScrollView *)arg1;
- (void)scrollViewDidEndLiveResize:(DVTSourceTextScrollView *)arg1;
- (void)scrollViewWillStartLiveResize:(DVTSourceTextScrollView *)arg1;
- (BOOL)scrollView:(DVTSourceTextScrollView *)arg1 shouldHandleScrollWheelEvent:(NSEvent *)arg2;
@end

