//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

//
// SDK Root: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk.sdk
//

#include "Shared.h"

#import "IDEAbstractFindNavigatorOutlineView.h"

#import "DVTEmptyContentPlaceholderContainer-Protocol.h"

@class NSFont, NSString;

@interface IDEFindNavigatorOutlineView : IDEAbstractFindNavigatorOutlineView <DVTEmptyContentPlaceholderContainer>
{
    BOOL _processingMouseEvent;
    int _emptyContentStringStyle;
    NSString *_emptyContentString;
    NSString *_emptyContentSubtitle;
    NSFont *_emptyContentFont;
}

@property(readonly) BOOL processingMouseEvent; // @synthesize processingMouseEvent=_processingMouseEvent;
@property(copy, nonatomic) NSFont *emptyContentFont; // @synthesize emptyContentFont=_emptyContentFont;
@property(nonatomic) int emptyContentStringStyle; // @synthesize emptyContentStringStyle=_emptyContentStringStyle;
@property(copy, nonatomic) NSString *emptyContentSubtitle; // @synthesize emptyContentSubtitle=_emptyContentSubtitle;
@property(copy, nonatomic) NSString *emptyContentString; // @synthesize emptyContentString=_emptyContentString;
// - (void).cxx_destruct;
- (BOOL)validateUserInterfaceItem:(id)arg1;
- (void)contextMenu_copy:(id)arg1;
- (void)copy:(id)arg1;
- (BOOL)dataSourceSupportsWritingToPasteboard;
- (void)mouseDown:(id)arg1;
- (void)viewWillDraw;

@end

