//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

//
// SDK Root: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX/Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk.sdk
//


@class IDENavigatorOutlineView;

@protocol IDENavigatorOutlineViewLoadingDelegate <NSObject>
- (void)outlineViewDidDrawInitialContent:(IDENavigatorOutlineView *)arg1;
- (void)outlineViewWillDrawInitialContent:(IDENavigatorOutlineView *)arg1;
@end

