//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

//
// SDK Root: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk.sdk
//

#include "Shared.h"

#import "DVTControllerContentView.h"

#import "IDEComparisonEditorScrollerAreaView-Protocol.h"

@class IDESourceCodeEditor, NSString, NSView;

@interface IDESourceEditorContentView : DVTControllerContentView <IDEComparisonEditorScrollerAreaView>
{
    IDESourceCodeEditor *_editor;
}

@property __weak IDESourceCodeEditor *editor; // @synthesize editor=_editor;
// - (void).cxx_destruct;
@property(readonly) NSView *viewToInstallScrollerIn;
- (void)primitiveInvalidate;
- (id)initWithFrame:(struct CGRect)arg1 editor:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) Class superclass;

@end

