//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

//
// SDK Root: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk.sdk
//

#include "Shared.h"

@class NSString;

@interface IDETabbedWindow : NSWindow <NSKeyedArchiverDelegate>
{
}

- (id)archiver:(id)arg1 willEncodeObject:(id)arg2;
- (id)dataByEncodingRestorableState;
- (void)restoreStateWithData:(id)arg1;
- (void)restoreStateWithCoder:(id)arg1;
- (void)closeOtherTabs:(id)arg1;
- (void)closeWindowAsTab:(id)arg1;
- (id)currentlySelectedTabbedWindow;
@property(setter=setTabBarIsVisible:) BOOL tabBarIsVisible;
- (BOOL)validateMenuItem:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) Class superclass;

@end

