//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

//
// SDK Root: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk.sdk
//


@class NSArray, NSString;
@protocol IDEBlueprint, IDETestable;

@protocol IDETestableProvider <NSObject>
@property(readonly) NSString *name;
@property(readonly, copy) NSArray *testables;
- (id <IDETestable>)testableForBlueprint:(id <IDEBlueprint>)arg1;
@end

