
#ifndef Xcode_h
#define Xcode_h

#import <Cocoa/Cocoa.h>
#import <Foundation/Foundation.h>

#import "../Shared Code/Xcode/DVTTextCompletionController.h"
#import "../Shared Code/Xcode/DVTTextCompletionDataSource.h"
#import "../Shared Code/Xcode/DVTMarkedScroller.h"
#import "../Shared Code/Xcode/IDESchemeActionCodeCoverageFile.h"
#import "../Shared Code/Xcode/IDEIssueManager.h"
#import "../Shared Code/Xcode/DVTNotificationToken.h"
#import "../Shared Code/Xcode/IDEAnalyzerResultsVisualization.h"
#import "../Shared Code/Xcode/IDEAnalyzerResultsExplorer.h"
#import "../Shared Code/Xcode/DVTScopeBarController.h"
#import "../Shared Code/Xcode/IDESingleFileProcessingToolbarController.h"
#import "../Shared Code/Xcode/DVTObservingToken.h"
#import "../Shared Code/Xcode/IDEBuildOperation.h"
#import "../Shared Code/Xcode/DVTSourceExpression.h"
#import "../Shared Code/Xcode/DVTControllerContentView.h"
#import "../Shared Code/Xcode/IDESourceKitAvailableRefactoring-Protocol.h"
#import "../Shared Code/Xcode/IDEIssueManager.h"
#import "../Shared Code/Xcode/IDEEditorDocument.h"
#import "../Shared Code/Xcode/IDEMediaResourceVariantContext.h"

#import "../Shared Code/Xcode/DVTDocumentLocation.h"
#import "../Shared Code/Xcode/DVTTextDocumentLocation.h"
#import "../Shared Code/Xcode/DVTFindPatternFieldEditor.h"
#import "../Shared Code/Xcode/DVTFindBarOptionsCtrl.h"
#import "../Shared Code/Xcode/DVTAnnotationManager.h"
#import "../Shared Code/Xcode/DVTAnnotationProvider.h"
#import "../Shared Code/Xcode/DBGBreakpointAnnotationProvider.h"
#import "../Shared Code/Xcode/DVTAnnotation.h"
#import "../Shared Code/Xcode/DBGBreakpointAnnotation.h"
#import "../Shared Code/Xcode/DVTTextStorage.h"
#import "../Shared Code/Xcode/DVTAnnotationManager.h"
#import "../Shared Code/Xcode/DVTFilePath.h"
#import "../Shared Code/Xcode/DVTTextSidebarView.h"
#import "../Shared Code/Xcode/DVTMacroExpansionScope.h"
#import "../Shared Code/Xcode/DVTMacroExpansionStringList_NonLiteral.h"
#import "../Shared Code/Xcode/DVTMacroDefinitionTable.h"
#import "../Shared Code/Xcode/DVTFindPatternTextField.h"
#import "../Shared Code/Xcode/DVTFontAndColorTheme.h"
#import "../Shared Code/Xcode/DVTUndoManagerDelegate-Protocol.h"
#import "../Shared Code/Xcode/DVTSourceCodeLanguage.h"
#import "../Shared Code/Xcode/DVTGeneratedContentProvider.h"
#import "../Shared Code/Xcode/DVTSourceModel.h"



#import "../Shared Code/Xcode/IDENavigatorOutlineView.h"
#import "../Shared Code/Xcode/IDEIssueNavigator.h"
#import "../Shared Code/Xcode/IDEIssueNavigableItem.h"
#import "../Shared Code/Xcode/IDEConsoleTextView.h"
#import "../Shared Code/Xcode/IDEEditorCoordinator.h"
#import "../Shared Code/Xcode/IDEEditorOpenSpecifier.h"
#import "../Shared Code/Xcode/IDEWorkspaceWindow.h"
#import "../Shared Code/Xcode/IDEWorkspaceWindowController.h"
#import "../Shared Code/Xcode/IDEWorkspaceTabController.h"
#import "../Shared Code/Xcode/IDEWorkspaceDocument.h"
#import "../Shared Code/Xcode/IDEWorkspace.h"
#import "../Shared Code/Xcode/IDERunContextManager.h"
#import "../Shared Code/Xcode/IDEScheme.h"
#import "../Shared Code/Xcode/IDELaunchSchemeAction.h"
#import "../Shared Code/Xcode/IDECommandLineArgumentEntry.h"
#import "../Shared Code/Xcode/IDEBreakpoint.h"
#import "../Shared Code/Xcode/IDEBreakpointManager.h"
#import "../Shared Code/Xcode/IDEStructureNavigator.h"
#import "../Shared Code/Xcode/IDEContainer.h"
#import "../Shared Code/Xcode/Xcode3Project.h"
#import "../Shared Code/Xcode/IDEContainerReloadingDelegate-Protocol.h"
#import "../Shared Code/Xcode/IDEDocumentController.h"
#import "../Shared Code/Xcode/IDEExecutionEnvironment.h"
#import "../Shared Code/Xcode/IDEBuildOperationQueueSet.h"
#import "../Shared Code/Xcode/IDETabbedWindow.h"
#import "../Shared Code/Xcode/IDENavigatorArea.h"
#import "../Shared Code/Xcode/IDEFindNavigator.h"
#import "../Shared Code/Xcode/IDEFindNavigatorOutlineView.h"
#import "../Shared Code/Xcode/IDEFindNavigatorQueryResultsController.h"
#import "../Shared Code/Xcode/IDEBatchFindAbstractResult.h"
#import "../Shared Code/Xcode/IDEBatchFindCallHierarchyResult.h"
#import "../Shared Code/Xcode/IDEBatchFindAbstractMatchResult.h"
#import "../Shared Code/Xcode/IDEBatchFindRootResult.h"
#import "../Shared Code/Xcode/IDEBatchFindFileResult.h"
#import "../Shared Code/Xcode/IDEEditorArea.h"
#import "../Shared Code/Xcode/IDEEditorContext.h"
#import "../Shared Code/Xcode/IDEEditor.h"
#import "../Shared Code/Xcode/IDEIssue.h"
#import "../Shared Code/Xcode/IDEFindNavigatorQueryParametersController.h"
#import "../Shared Code/Xcode/IDEProgressSearchField.h"
#import "../Shared Code/Xcode/_IDEProgressSearchFieldCell.h"
#import "../Shared Code/Xcode/IDEFindNavigatorPathControl.h"
#import "../Shared Code/Xcode/IDEFindNavigatorScopeChooserController.h"
#import "../Shared Code/Xcode/DVTScopeBarButton.h"
#import "../Shared Code/Xcode/IDEBatchFindNamedScope.h"

#import "../Shared Code/Xcode/XCCompilerSpecification.h"
#import "../Shared Code/Xcode/XCBuildPhaseDGSnapshot.h"
#import "../Shared Code/Xcode/XCMacroExpansionScope.h"
#import "../Shared Code/Xcode/XCBuildFileRefArrayDGSnapshot.h"
#import "../Shared Code/Xcode/XCBuildFileRefDGSnapshot.h"

#import "../Shared Code/Xcode/DBGLLDBDebugLocalService.h"
#import "../Shared Code/Xcode/DBGLLDBLauncher.h"

#import "../Shared Code/Xcode/PBXFileType.h"

#import "../Shared Code/Xcode/NSCarbonMenuImpl.h"

#endif /* XCFixin_EmulateVisualStudio_h */
