//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//
#pragma once

#pragma mark Blocks

typedef void (^CDUnknownBlockType)(void); // return type and parameters are unknown

#pragma mark Named Structures

struct _DVTFindBarFlags {
    unsigned int findResultsValid:1;
    unsigned int userIsChangingFindString:1;
    unsigned int userIsChangingReplaceString:1;
    unsigned int userIsRestoringHistory:1;
    unsigned int dismissRestoresSelection:1;
    unsigned int ignoreNextInvalidate:1;
    unsigned int viewIsInstalled:1;
    unsigned int _reserved:29;
};

struct _DVTIncrementalFindBarFlags {
    unsigned int currentResultSet:1;
    unsigned int foundResultsSet:1;
    unsigned int textFindableImplementsSupportedMatchingOptions;
    unsigned int _reserved:30;
};

struct _DVTLayoutManagerFlags {
    unsigned int disableAnnotationAdjustment:1;
    unsigned int severeBubbleAnnotationsMiniaturized:1;
};

struct _DVTTextChangeEntry {
    struct _NSRange _field1;
    long long _field2;
    struct _NSRange _field3;
    long long _field4;
    double _field5;
};

struct _DVTTextLineOffsetTable {
    unsigned long long capacity;
    unsigned long long count;
    unsigned long long *offsets;
    unsigned long long deferredAdjustmentIndex;
    long long deferredAdjustment;
};

#pragma mark Typedef'd Structures

typedef struct {
    double minX;
    double maxX;
    double minY;
    double maxY;
} CDStruct_bf6d4a14;

