//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk.sdk
//

@class DVTDualProxyWindowTitleView, NSString, NSURL;

@interface DVTDualProxyWindow : NSWindow
{
    DVTDualProxyWindowTitleView *_titleView;
    NSURL *_secondaryRepresentedURL;
    NSString *_titlePrefix;
    CDUnknownBlockType _primaryRepresentedDocumentBlock;
    CDUnknownBlockType _secondaryRepresentedDocumentBlock;
}

- (id)_accessibilityTitleCell;
- (struct CGRect)_accessibilityTitleRect;
- (id)accessibilityTitleUIElementAttribute;
- (void)dvt_updateTitle:(id)arg1;
- (void)setTitle:(id)arg1;
- (id)title;
@property(copy) CDUnknownBlockType secondaryRepresentedDocumentBlock;
@property(copy) CDUnknownBlockType primaryRepresentedDocumentBlock;
@property(copy) NSString *titlePrefix;
@property(copy) NSURL *secondaryRepresentedURL;
- (void)setRepresentedURL:(id)arg1;
- (void)invalidateTitle;
- (BOOL)_isTitleHidden;
- (void)close;
- (id)dvt_titleView;

@end

