//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//
// SDK Root: /Developer/SDKs/MacOSX/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk.sdk
//

@class DVTFindPattern;

@protocol DVTFindPatternManager <NSObject>
- (id )replaceFieldForField:(id )arg1;
- (id )findFieldForField:(id )arg1;

@optional
- (BOOL)supportsPatterns;
- (void)findPatternField:(id )arg1 findPatternDoubleClicked:(DVTFindPattern *)arg2;
@end

